# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-04 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='verified_quality',
            field=models.IntegerField(default=0),
        ),
    ]
