# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-04 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_verified_quality'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='coeff',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='percentage',
            field=models.FloatField(default=0.0),
        ),
    ]
