# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-04 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20170804_0600'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='product_imgs'),
        ),
    ]
